### ISSUE TITLE
nil error when running just "Heroku"

### ISSUE THREAD

**Issue by coreyhaines** [heroku/legacy-cli#2061]
When I run
`heroku`

I get this error
```
ᕕ( ᐛ )ᕗ 🐈 $ heroku
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       can't convert nil into String (TypeError)
    Command:     heroku 
    Version:     heroku-toolbelt/3.43.9999 (x86_64-darwin10.8.0) ruby/1.9.3
    Error ID:    3b2cf29936134dad921c9af4f8d49364```

Here's the stack trace from the log

```
can't convert nil into String 
1014 /Users/coreyhaines/.heroku/client/lib/heroku/jsplugin.rb:127:in `system' 
1015 /Users/coreyhaines/.heroku/client/lib/heroku/jsplugin.rb:127:in `run' 
1016 /Users/coreyhaines/.heroku/client/lib/heroku/jsplugin.rb:17:in `try_takeover' 
1017 /Users/coreyhaines/.heroku/client/lib/heroku/cli.rb:29:in `start' 
1018 /usr/local/heroku/bin/heroku:24:in `<main>' ```

**Comment by dickeyxxx** [comment]
It's possible it may fix itself if you run `heroku update`, but it would be best to reinstall. Right now it's still using the same legacy ruby code that was installed when you first installed the CLI and it's not interfacing with the new node code right. I'm not sure what the real problem is, but a reinstall should definitely fix it since it's in that legacy codebase.

**Comment by coreyhaines** [comment]
`heroku update` crashed. However, I reinstalled it via homebrew, and it works now. Thanks!
