### ISSUE TITLE
pg:psql might not work on windows?

### ISSUE THREAD

**Issue by will** [heroku/legacy-cli#334]
from someone writing into to devcenter feedback

After installing postgresql on windows, I'm unable to run heroku pg:psql. It gives me the message "The local psql command could not be located". I tried adding the path to the PATH environment variable. I'm able to run the command myself (by typing psql), but heroku still can't find the executable.

**Comment by sethlivingston** [comment]
Remove the quotes fixed my problem.

**Comment by Mickelain** [comment]
A reboot fixed it for me. I think because that forces cygwin to update its path.

**Comment by MalikRumi** [comment]
@will I am on Windows 8.1 with Postgres 9.4 on AMD64. I have Postgres in my PATH, so I no longer get 'the local psql could not be located'. However, it still does not work for me. Here is my output:

$ PGUSER=postgres PGPASSWORD=password heroku pg:push baillee HEROKU_POSTGRESQL_
MAROON_URL --app myapp
Password:
pg_dump: reading schemas
pg_dump: reading user-defined tables
...etc...
pg_dump: saving database definition
pg_restore: [archiver] did not find magic string in file header
pg_dump: [custom archiver] could not write to output file: Invalid argument

I just read your post on SO http://stackoverflow.com/questions/25870388/heroku-pgpull-failing-to-populate-schema. Surely there are other people on Windows who have successfully uploaded a database to Heroku. How are they doing it? Clearly I can't stay on Heroku if I can't use my database.

I googled gen_pg_*_commands and got nothing.  This post http://www.postgresql.org/message-id/4CE6C95F.7090001@gmail.com says use psql, and not pg_restore, but that failed for me because I have to retype that long password by hand - assuming it is the right password. 

$ pg_restore -d baillee > HEROKU_POSTGRESQL_MAGENTA just sits there and blinks at me.
Please advise. Thanks.

**Comment by will** [comment]
> I just read your post on SO http://stackoverflow.com/questions/25870388/heroku-pgpull-failing-to-populate-schema. Surely there are other people on Windows who have successfully uploaded a database to Heroku. How are they doing it? Clearly I can't stay on Heroku if I can't use my database.
Yes, you can upload a database, you just can't use the heroku command to do it.

> $ pg_restore -d baillee > HEROKU_POSTGRESQL_MAGENTA just sits there and blinks at me.
Please advise. Thanks.
you need to look at the full url with `heroku config` of the database and first use `pg_dump` to take a dump of your local database, and then `PG_PASSWORD=<PASSWORD> pg_restore --verbose --clean --no-acl --no-owner -h <HOST> -U <USER> -d <DB> -p <PORT> <DUMPFILE>` if you want to restore a local dump to heroku

**Comment by MalikRumi** [comment]
I could not get Git Bash to accept these commands. It kept saying "pg_dump:
too many command-line arguments (first is "-f")"   Is this a Windows issue?

But uploading to Dropbox and then restoring from there worked, so it is
there without all the flags. Now I have an import error so until that is
resolved I don't really know what I have for a db. Thx.

**Comment by PGarzoAr** [comment]
thx stprior and MrSwitch with your solutions it worked

**Comment by thedomain** [comment]
MrSwitch --thanks

**Comment by hsian** [comment]
@MrSwitch   thanks a lot!
