### ISSUE TITLE
heroku/updater.rb error

### ISSUE THREAD

**Issue by cfc1020** [heroku/legacy-cli#814]
Win7 x64 
C:\Program Files\Heroku>heroku
C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:164:in `spawn': No such file
 or directory - open (Errno::ENOENT)
        from C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:164:in`backgro
und_update!'
        from C:/Program Files (x86)/Heroku/lib/heroku/updater.rb:144:in `inject_
libpath'
        from C:/Program Files (x86)/Heroku/bin/heroku:24:in`<main>'

**Comment by MalikRumi** [comment]
@dickeyxxx Well, since you invited further comment, I will. Here is my error:
←[0KRunning... 0.00BC:/Users/.heroku/client/lib/heroku/cli.rb:45:in ``': No such file or directory - stty ica
non echo (Errno::ENOENT)
        from C:/Users/.heroku/client/lib/heroku/cli.rb:45:in `rescue in start'
        from C:/Users/.heroku/client/lib/heroku/cli.rb:35:in `start'
        from C:/Program Files/Heroku/bin/heroku:29:in `<main>'
Terminate batch job (Y/N)? N
(green) PS G:\blue\BLUE> heroku pg:backups
=== Backups
 !    No backups. Capture one with `heroku pg:backups capture`.
(green) PS G:\blue\BLUE>

This happens when I am trying to import a database. I saw some of these issues had to do with using, or not using, a latin username. I don't think that's my issue. I am on Windows 8.1. 

This guy  https://github.com/heroku/heroku/issues/1093  seems to have the same error but a very different fix. I look forward to your assistance.

**Comment by dickeyxxx** [comment]
Would you mind trying again after running `heroku update`? I put a small fix around this error.

**Comment by MalikRumi** [comment]
Ok, it says it updated, but now I am back to my old database errors.
